# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b71a939d9db982487be2e55286fbc6a"
name = "teste-neki-hotsite"
handle = "teste-neki-hotsite"
application_url = "https://albert-narrative-periods-brooklyn.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teste-neki-it.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_script_tags,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://albert-narrative-periods-brooklyn.trycloudflare.com/auth/callback",
  "https://albert-narrative-periods-brooklyn.trycloudflare.com/auth/shopify/callback",
  "https://albert-narrative-periods-brooklyn.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
